services:
  openvpn-as:
    image: openvpn/openvpn-as:latest
    container_name: openvpn-access-server
    restart: unless-stopped
    
    ports:
      - "943:943"       # Admin & Client Web UI (HTTPS)
      - "1194:1194/udp" # OpenVPN UDP port
    
    cap_add:
      - NET_ADMIN
      - MKNOD
    
    devices:
      - /dev/net/tun:/dev/net/tun
    
    volumes:
      - openvpn-data:/opt/openvpn-as

volumes:
  openvpn-data: